SUBDIRS = ext.d

EXTRA_DIST = \
	docker/README.md \
	docker/sandbox.sh \
	docker/common/build-mc.sh \
	docker/common/check-remote.sh \
	docker/common/fixtures.sh \
	docker/common/zshrc \
	docker/common/remote/Dockerfile.remote \
	docker/common/remote/entrypoint-remote.sh \
	docker/common/remote/smb.conf \
	docker/common/remote/vsftpd.conf \
	docker/scenarios/arcmc/Dockerfile.mc \
	docker/scenarios/arcmc/docker-compose.yml \
	docker/scenarios/arcmc/README.md
